### ISSUE TITLE
python3 ? 

### ISSUE THREAD

**Issue by colindaven** [benoukraflab/NanoVar---archived#1]
Hi, Python2 is only supported till 2020 - that's six months. Any plans for a python3 version ?

cheers,
Colin

**Comment by benoukraflab** [comment]
Hi Colin,

Yes, the Python3 version of NanoVar is coming soon. It will be uploaded to the developer release Github repository https://github.com/cytham/nanovar-dev around next week.

Thanks!

Cheers,
cytham

**Comment by cytham** [comment]
Hi Colin,

The Python 3 version of NanoVar is pre-released on the develop branch:  https://github.com/cytham/nanovar-dev. Feel free to try it out!

Thanks
cytham

**Comment by colindaven** [comment]
Nice, thanks, I'll have a look soon.
