### ISSUE TITLE
can not install NanoVar

### ISSUE THREAD

**Issue by LinXialab** [benoukraflab/NanoVar---archived#3]
Hi, 

We missed a problem when install NanoVar:

~/tools/NanoVar-master$ make
Dependency error: bedtools required to be version 2.26.0 or greater
make: *** [checkversions] Error 1
~/tools/NanoVar-master$ bedtools --version
bedtools v2.27.1

Could you please help us to solve this problem?

**Comment by benoukraflab** [comment]
Hi LinXialab,

Thanks for using NanoVar.

Can you please show me the output when you do ./configure?
Also, can you execute "which bedtools" and show me the output.

You can also try configuring with bedtools path. (e.g. "./configure --with-bedtools=/path/to/bedtools")  And then try make again.

Thanks
cytham

**Comment by LinXialab** [comment]
Hi,

The output when we do ./configure was:
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for python2.7... /home/*/software/Anaconda2/bin/python2.7
checking for seq... /usr/bin/seq
checking for touch... /usr/bin/touch
checking for zcat... /bin/zcat
checking for md5sum... /usr/bin/md5sum
checking for samtools... /mnt/*/Tools/samtools-1.8//samtools
checking for bedtools... /home/*/bedtools2/bin//bedtools
checking for bowtie2... /usr/bin/bowtie2
checking for bowtie2-build... /usr/bin/bowtie2-build
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating scripts/Makefile
(Sorry, some detail of the path we can not show you, so i used * to replace)

And the output for "which bedtools" was:
/home/*/bedtools2/bin//bedtools

In addition, the output for "/home/*/bedtools2/bin//bedtools --version" was:
bedtools v2.27.1

**Comment by cytham** [comment]
Hi LinXialab,

Thanks for the output.

1) May I clarify that the * in "_checking for bedtools... /home/*/bedtools2/bin//bedtools_" is the same as the * in '"_which bedtools" was: /home/*/bedtools2/bin//bedtools_' ?

2) Can you please execute "_grep 'bedversion =' Makefile_" and show me the output?

3) Please try to configure by specifying your bedtools path. (i.e. "_./configure --with-bedtools=/home/*/bedtools2/bin//bedtools_") and try to make again.

Thanks
cytham

**Comment by LinXialab** [comment]
Hi, 
Thanks for your reply.
1. Yes, they are same.
2. The output of "grep 'bedversion =' Makefile" was:
bedversion = 2.27.1
3. I have tried the new comments,  and got a new error for the version of bowtie2. I will look forward how to solve the new problem.
Thank you so much!

**Comment by cytham** [comment]
Hi LinXialab,

Thanks for your reply.

Do you intend to use NGS short-reads? if not, you can configure with bowtie2 disabled (i.e. "_./configure --with-bedtools=/home/*/bedtools2/bin//bedtools --disable-bowtie2_")

Thanks
cytham

**Comment by LinXialab** [comment]
Hi,

I have install Nanovar successfully, thank you for your help!
Best Wishes！
