### ISSUE TITLE
Error: SV Overlap file required

### ISSUE THREAD

**Issue by LeaveYeah** [benoukraflab/NanoVar---archived#4]
Error encountered: SV Overlap file required

**Comment by cytham** [comment]
Hi LeaveYeah,

Thank you for your post.

1) Is there any other error before this error?
2) Can you show me the contents of the NanoVar.log file?
3) NanoVar requires BEDTools, do you have BEDTools installed and in the PATH?
4) When installing NanoVar, did you carry out "make check" and was it successful?

Best,
cytham

**Comment by LeaveYeah** [comment]
Hi, cytham,
1. There is no errors before this error.
2. Please see the log file as attached
3. Bedtools is installed and in the path
4. I carry out "make check". It is not successful. It says intermediate test file is contaminated.
[17-Aug_18-13-30_NanoVar.log](https://github.com/benoukraflab/NanoVar/files/3517045/17-Aug_18-13-30_NanoVar.log)

**Comment by LeaveYeah** [comment]
In the "make check" step, it says "***OverlapANN file required!***- ]  (40%)".

**Comment by cytham** [comment]
Hi LeaveYeah,

Thanks for the reply.

May I check if your log file is complete? It should end with the error line "SV Overlap file required". Or else, is it possible that you might have accidentally moved the log file during the run?

Can you please rebuild NanoVar using the following commands in the NanoVar directory:
make distclean
./configure --disable-bowtie2
make
make check

Please send me the log file and the commandlog file if the error persist. 

Can you please let me know your GNU awk version (by doing "awk --version"), bedtools version and operating system.

Thanks
cytham

**Comment by sage-wright** [comment]
Hi cytham, 

I've also run into the same issue with `***Overlap ANN file required!*** ]  (40%)` during "make check".

I assume I'm likely having a similar/identical issue as LeaveYeah, so here are the details you asked for, but in my situation. My GNU awk version is 3.1.7, and my bedtools is 2.27.1.  I'm using a x86_64 Red Hat Linux cluster.

I tried to switch to the dev version using Python 3 to see if that would fix things, but I ran into the exact same issue. Here's the log file from everything after "make distclean". 

[commands-and-output.log](https://github.com/benoukraflab/NanoVar/files/3521227/commands-and-output.log)

Thanks for your help!
Sage

**Comment by sage-wright** [comment]
I'm not sure what overlap file seems to be missing as all of the ones referenced in the commandlogs and regular log seem to be present. 

Here's the log files from the testing stages.
[20-Aug~13-00-42_NanoVar.log](https://github.com/benoukraflab/NanoVar/files/3521771/20-Aug.13-00-42_NanoVar.log)
[20-Aug~13-00-42_NanoVar.command.log](https://github.com/benoukraflab/NanoVar/files/3521772/20-Aug.13-00-42_NanoVar.command.log)

Edited: I did find that in `/test/testout/nanovar_run/hsblast_longreads/` both `lread_test.hsblast-ref.SV0.95.parse150.1-13.7.overlap.ANN0.tsv` and `lread_test.hsblast-ref.SV0.95.parse150.1-13.7.overlap.ANN.tsv` are empty. They're made on line 14 of the NanoVar command log, during the keras_ANN_inference.py step. All the subsequent steps were enacted on empty files. I am not sure if this is what is intended.

**Comment by LeaveYeah** [comment]
Hi, cytham,

Sorry for the late reply. I rebuilt NanoVar after "make distclean". The problem still persists. Below is the version of my awk, bedtools and operating systm and logs of building and testing.
GNU Awk 4.1.3, bedtools v2.26.0, CentOS release 6.10.
[build and test.log](https://github.com/benoukraflab/NanoVar/files/3522116/build.and.test.log)

**Comment by cytham** [comment]
Hi Sage,

Thanks for raising the issue and your efforts in troubleshooting. I apologize for the inconvenience caused.

There seem to be a problem in generating the file "lread_test.hsblast-ref.SV0.95.parse150.1-13.7.overlap.ANN.tsv" which resulted in all the downstream files being empty.

Can you please try the following commands and let me know if it is successful?

#Start of commands
source /hpc/home/szw190/NANOPORE/sv_callers/NanoVar/nv_virtualenv/bin/activate

python /hpc/home/szw190/NANOPORE/sv_callers/NanoVar/scripts/keras_ANN_inference.py lread_test.hsblast-ref.SV0.95.parse150.1-13.7.overlap.tsv lread_test.hsblast-ref.SV0.95.parse150.tsv /hpc/home/szw190/NANOPORE/sv_callers/NanoVar/model/ANN.E100B400L2N12-5D0.2SGDsee30_het_v5.h5 13.7 4.14419555556 overlap > test1.tsv

deactivate
#End of commands
(I assumed you haven't deleted/make clean the output files of the make check.)

Thanks

**Comment by cytham** [comment]
Hi LeaveYeah,

Thanks for the information you provided.

Can you please provide me the "commandlog" file after doing the make check? It should be located either in the /NanoVar/test/testout/ or /NanoVar/test/testout/nanovar_run/ directories.

Thanks

**Comment by LeaveYeah** [comment]
Here it is.
[17-Aug_18-13-30_NanoVar.log.txt](https://github.com/benoukraflab/NanoVar/files/3522240/17-Aug_18-13-30_NanoVar.log.txt)

**Comment by LeaveYeah** [comment]
Here it is cytham.
[20-Aug_13-24-52_NanoVar.commandlog.txt](https://github.com/benoukraflab/NanoVar/files/3522243/20-Aug_13-24-52_NanoVar.commandlog.txt)

**Comment by sage-wright** [comment]
Thanks cytham! i tried the commands, and it looks like the issue is with TensorFlow:

```
Traceback (most recent call last):
  File "/hpc/home/szw190/NANOPORE/sv_callers/NanoVar/scripts/keras_ANN_inference.py", line 38, in <module>
    from keras.models import Sequential
  File "/hpc/home/szw190/NANOPORE/sv_callers/NanoVar/nv_virtualenv/lib/python2.7/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/hpc/home/szw190/NANOPORE/sv_callers/NanoVar/nv_virtualenv/lib/python2.7/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/hpc/home/szw190/NANOPORE/sv_callers/NanoVar/nv_virtualenv/lib/python2.7/site-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/hpc/home/szw190/NANOPORE/sv_callers/NanoVar/nv_virtualenv/lib/python2.7/site-packages/keras/backend/__init__.py", line 89, in <module>
    from .tensorflow_backend import *
  File "/hpc/home/szw190/NANOPORE/sv_callers/NanoVar/nv_virtualenv/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "/hpc/home/szw190/NANOPORE/sv_callers/NanoVar/nv_virtualenv/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/hpc/home/szw190/NANOPORE/sv_callers/NanoVar/nv_virtualenv/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/hpc/home/szw190/NANOPORE/sv_callers/NanoVar/nv_virtualenv/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/hpc/home/szw190/NANOPORE/sv_callers/NanoVar/nv_virtualenv/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/hpc/home/szw190/NANOPORE/sv_callers/NanoVar/nv_virtualenv/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/hpc/home/szw190/NANOPORE/sv_callers/NanoVar/nv_virtualenv/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.7' not found (required by /hpc/home/szw190/NANOPORE/sv_callers/NanoVar/nv_virtualenv/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

The virtualenv is using these python & gcc versions: 
```
Python 2.7.14 (default, Jan 31 2018, 02:12:13)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-18)] on linux2
```

Using different GCC versions end up producing either very similar errors; i.e., different ImportErrors, like the `/lib64/libc.so.6: version 'GLIBC_2.16' not found` that LeaveYeah reported when I use v8.2.0, or a `Bus Error (core dumped)` if I use v9.1.0. Earlier versions between 8.2.0 and 4.4.7 end up producing the same ImportError.

**Comment by cytham** [comment]
Thanks LeaveYeah

Can you please try the following commands and let me know if there's an error.

#Start of commands
source /data2/junwenwang/m204333/Project/NanoVar/nv_virtualenv/bin/activate

python /data2/junwenwang/m204333/Project/NanoVar/scripts/keras_ANN_inference.py lread_test.hsblast-ref.SV0.95.parse150.1-13.7.overlap.tsv lread_test.hsblast-ref.SV0.95.parse150.tsv /data2/junwenwang/m204333/Project/NanoVar/model/ANN.E100B400L2N12-5D0.2SGDsee30_het_v5.h5 13.7 4.14419555556 overlap > test1.tsv

deactivate
#End of commands

Thanks

**Comment by LeaveYeah** [comment]
Hi, I get the same error as Sage.
`Traceback (most recent call last):
  File "/data2/junwenwang/m204333/Project/NanoVar/scripts/keras_ANN_inference.py", line 38, in <module>
    from keras.models import Sequential
  File "/data2/junwenwang/m204333/Project/NanoVar/nv_virtualenv/lib/python2.7/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/data2/junwenwang/m204333/Project/NanoVar/nv_virtualenv/lib/python2.7/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/data2/junwenwang/m204333/Project/NanoVar/nv_virtualenv/lib/python2.7/site-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/data2/junwenwang/m204333/Project/NanoVar/nv_virtualenv/lib/python2.7/site-packages/keras/backend/__init__.py", line 89, in <module>
    from .tensorflow_backend import *
  File "/data2/junwenwang/m204333/Project/NanoVar/nv_virtualenv/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "/data2/junwenwang/m204333/Project/NanoVar/nv_virtualenv/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/data2/junwenwang/m204333/Project/NanoVar/nv_virtualenv/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/data2/junwenwang/m204333/Project/NanoVar/nv_virtualenv/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/data2/junwenwang/m204333/Project/NanoVar/nv_virtualenv/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/data2/junwenwang/m204333/Project/NanoVar/nv_virtualenv/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/data2/junwenwang/m204333/Project/NanoVar/nv_virtualenv/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: /lib64/libc.so.6: version `GLIBC_2.16' not found (required by /data2/junwenwang/m204333/Project/NanoVar/nv_virtualenv/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.`

**Comment by LeaveYeah** [comment]
Hi, cytham, this is what I've encountered, consistent to what Sage has tested.
```
Using TensorFlow backend.
Traceback (most recent call last):
  File "/data2/junwenwang/m204333/Project/NanoVar/scripts/keras_ANN_inference.py", line 38, in <module>
    from keras.models import Sequential
  File "/data2/junwenwang/m204333/Project/NanoVar/nv_virtualenv/lib/python2.7/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/data2/junwenwang/m204333/Project/NanoVar/nv_virtualenv/lib/python2.7/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/data2/junwenwang/m204333/Project/NanoVar/nv_virtualenv/lib/python2.7/site-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/data2/junwenwang/m204333/Project/NanoVar/nv_virtualenv/lib/python2.7/site-packages/keras/backend/__init__.py", line 89, in <module>
    from .tensorflow_backend import *
  File "/data2/junwenwang/m204333/Project/NanoVar/nv_virtualenv/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "/data2/junwenwang/m204333/Project/NanoVar/nv_virtualenv/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/data2/junwenwang/m204333/Project/NanoVar/nv_virtualenv/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/data2/junwenwang/m204333/Project/NanoVar/nv_virtualenv/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/data2/junwenwang/m204333/Project/NanoVar/nv_virtualenv/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/data2/junwenwang/m204333/Project/NanoVar/nv_virtualenv/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/data2/junwenwang/m204333/Project/NanoVar/nv_virtualenv/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: /lib64/libc.so.6: version `GLIBC_2.16' not found (required by /data2/junwenwang/m204333/Project/NanoVar/nv_virtualenv/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Comment by cytham** [comment]
I'm not sure if this will work, but it may be worth a try to upgrade tensorflow.

Try:
```
source /hpc/home/szw190/NANOPORE/sv_callers/NanoVar/nv_virtualenv/bin/activate

pip install --ignore-installed --upgrade tensorflow==1.9

python /hpc/home/szw190/NANOPORE/sv_callers/NanoVar/scripts/keras_ANN_inference.py lread_test.hsblast-ref.SV0.95.parse150.1-13.7.overlap.tsv lread_test.hsblast-ref.SV0.95.parse150.tsv /hpc/home/szw190/NANOPORE/sv_callers/NanoVar/model/ANN.E100B400L2N12-5D0.2SGDsee30_het_v5.h5 13.7 4.14419555556 overlap > test1.tsv

deactivate
```

**Comment by sage-wright** [comment]
No change-- the same issue happens. When I look at similar issues in the Tensorflow github page, they seem to suggest upgrade gcc when you downgrade Tensorflow. I'll try again with an upgraded gcc version... which changes nothing as well. 

I'm going to try and edit the requirement.txt file to see if an earlier change will cause a difference, since I noticed that tensorflow's older versions are still hanging around, as are all of the old numpys. I'm not sure if the right version is being used...  and no change.

**Comment by cytham** [comment]
Hi Sage,

Thanks for trying by upgrading gcc.

Please try the following and show me the output:
```
# To check if you have other libstdc++.so.6.x.x
locate libstdc++.so.6

# For all libstdc++.so.6.x.x versions found, check CXXABI versions
strings /path/to/libstdc++.so.6.x.x | grep CXXABI_
```
Thanks
 
Hi LeaveYeah,

Please try the following too:
```
# To check if you have other libc.so.6.x.x
locate libc.so.6

# For all libc.so.6.x.x versions found, check GLIBC versions
strings  /path/to/libc.so.6.x.x | grep GLIBC_
```

Thanks

**Comment by sage-wright** [comment]
Thank you for your help!

Here's the output of the commands:

> locate libstdc++.so.6
```
/opt/commvault/Base64/libstdc++.so.6
/opt/commvault/CVMedia/11.0.0/Unix/linux-x8664/linux-glibc2.3-x86_64/BinaryPayLoad/libstdc++.so.6.gz
/usr/lib/libstdc++.so.6
/usr/lib/libstdc++.so.6.0.13
/usr/lib64/libstdc++.so.6
/usr/lib64/libstdc++.so.6.0.13
/usr/local/BelMonitor/libstdc++.so.6
/usr/local/BelMonitor/libstdc++.so.6.0.3
/usr/share/gdb/auto-load/usr/lib/libstdc++.so.6.0.13-gdb.py
/usr/share/gdb/auto-load/usr/lib/libstdc++.so.6.0.13-gdb.pyc
/usr/share/gdb/auto-load/usr/lib/libstdc++.so.6.0.13-gdb.pyo
/usr/share/gdb/auto-load/usr/lib64/libstdc++.so.6.0.13-gdb.py
/usr/share/gdb/auto-load/usr/lib64/libstdc++.so.6.0.13-gdb.pyc
/usr/share/gdb/auto-load/usr/lib64/libstdc++.so.6.0.13-gdb.pyo
```

The second set of outputs:

> strings /opt/commvault/Base64/libstdc++.so.6 | grep CXXABI_
```
CXXABI_1.3
CXXABI_1.3.1
CXXABI_1.3.2
CXXABI_1.3.3
CXXABI_1.3.4
CXXABI_1.3.5
CXXABI_1.3.6
CXXABI_1.3.7
CXXABI_1.3.8
CXXABI_1.3.9
CXXABI_TM_1
CXXABI_FLOAT128
```

> /opt/commvault/CVMedia/11.0.0/Unix/linux-x8664/linux-glibc2.3-x86_64/BinaryPayLoad/libstdc++.so.6.gz

`(no results)`

> /usr/lib/libstdc++.so.6
/usr/lib/libstdc++.so.6.0.13
/usr/lib64/libstdc++.so.6
/usr/lib64/libstdc++.so.6.0.13
```
CXXABI_1.3
CXXABI_1.3.1
CXXABI_1.3.2
CXXABI_1.3.3
```

> /usr/local/BelMonitor/libstdc++.so.6
/usr/local/BelMonitor/libstdc++.so.6.0.3
```
CXXABI_1.3
CXXABI_1.3.1
```

and 

> /usr/share/gdb/auto-load/usr/lib/libstdc++.so.6.0.13-gdb.py
/usr/share/gdb/auto-load/usr/lib/libstdc++.so.6.0.13-gdb.pyc
/usr/share/gdb/auto-load/usr/lib/libstdc++.so.6.0.13-gdb.pyo
/usr/share/gdb/auto-load/usr/lib64/libstdc++.so.6.0.13-gdb.py
/usr/share/gdb/auto-load/usr/lib64/libstdc++.so.6.0.13-gdb.pyc
/usr/share/gdb/auto-load/usr/lib64/libstdc++.so.6.0.13-gdb.pyo

`(no results)`


The initial error says that `/usr/lib64/libstdc++.so.6: version 'CXXABI_1.3.7' not found` which is accurate! I only have up to 1.3.3 in that directory. But I do have version 1.3.7 in /opt/commvault/Base64/libstdc++.so.6. I'll try to use the fixes suggested in [this](https://stackoverflow.com/questions/39844772/cxxabi-1-3-8-not-found-in-tensorflow-gpu-install-from-source) StackOverflow question and let you know how that goes. 

Making a soft link in /nv_virtualenv/lib/python2.7/site-packages/ seemed to help: `ln -s /opt/commvault/Base64/libstdc++.so.6 libstdc++.so.6`, but then I ran into another issue:
```
ImportError: /usr/lib64/libstdc++.so.6: version 'GLIBCXX_3.4.17' not found (required by /hpc/home/szw190/NANOPORE/sv_callers/NanoVar/nv_virtualenv/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)
```

This also exists in /opt/commvault/Base64/libstdc++.so.6, but the soft-link does not seem to help it.

**Comment by cytham** [comment]
Hi Sage,

Thanks for showing the output, they are really helpful!

Do you think it will work if you create the soft link to ```/usr/lib64/libstdc++.so.6``` instead of ```/nv_virtualenv/lib/python2.7/site-packages/```?
```
#First rename /usr/lib64/libstdc++.so.6 to something else e.g. /usr/lib64/libstdc++.so.6_original
sudo mv /usr/lib64/libstdc++.so.6 /usr/lib64/libstdc++.so.6_original

#Create the soft link
sudo ln -s /opt/commvault/Base64/libstdc++.so.6 /usr/lib64/libstdc++.so.6
```

**Comment by sage-wright** [comment]
It probably would! But I don't have sudo access which complicates things.

I'll contact the sys admin now that I'm pretty sure we've figured out what the issue is. Thank you so much for all of your assistance!

**Comment by cytham** [comment]
Oh I see. 

Maybe you can try to add it to your LD_LIBRARY_PATH in the meantime and see if it works.

```
export LD_LIBRARY_PATH=/opt/commvault/Base64/:$LD_LIBRARY_PATH
```

**Comment by sage-wright** [comment]
Unfortunately, that didn't work.

**Comment by cytham** [comment]
As you have previously altered certain things in nv_virtualenv, I would suggest you to do a clean reinstallation of NanoVar and try ```make check``` again after exporting the new LD_LIBRARY_PATH.

**Comment by sage-wright** [comment]
Great idea. I had forgotten that I had messed around a lot with the virtualenv. That actually did help with the GLIBCXX_ version! I then ran into the issue with the GLIBC_2.16 version that LeaveYeah has, and found that my machine does not have this version available anywhere.

I install GLIBC_2.16 locally and used patchelf to connect the GLIBC_2.16 to the virtualenv's python as recommended in [this](https://stackoverflow.com/questions/847179/multiple-glibc-libraries-on-a-single-host/851229#851229) question, but that ended up breaking the entire virtualenv's python due to an issue with shared libraries: `python: error while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file: No such file or directory`. Most all suggestions to fix _this_ issue either required root access or reinstallation of python, which defeats the purpose of using patchelf's fix to connect with the new GLIBC_2.16 version I was trying to use.

**Comment by cytham** [comment]
Thanks, that's great!
I have created a side branch of NanoVar which contains the updated lib. You can clone it by specifying the branch "lib" as shown below.

```
git clone --single-branch --branch lib https://github.com/benoukraflab/NanoVar.git
```

Hope it works

**Comment by sage-wright** [comment]
Oh no!! It didn't work. It still goes back to the GLIBC version error. Thank you so much, though, for all of the effort you are putting in to helping me. I really appreciate it. You have gone above and beyond what I expected.

Here's the latest error message:

```
Traceback (most recent call last):  (32%)
  File "/hpc/home/szw190/NANOPORE/sv_callers/second/NanoVar/scripts/nv_lcov_outlier.py", line 29, in <module>
    import matplotlib.pyplot as plt
  File "/hpc/home/szw190/NANOPORE/sv_callers/second/NanoVar/nv_virtualenv/lib/python2.7/site-packages/matplotlib/pyplot.py", line 31, in <module>
    import matplotlib.colorbar
  File "/hpc/home/szw190/NANOPORE/sv_callers/second/NanoVar/nv_virtualenv/lib/python2.7/site-packages/matplotlib/colorbar.py", line 32, in <module>
    import matplotlib.artist as martist
  File "/hpc/home/szw190/NANOPORE/sv_callers/second/NanoVar/nv_virtualenv/lib/python2.7/site-packages/matplotlib/artist.py", line 16, in <module>
    from .path import Path
  File "/hpc/home/szw190/NANOPORE/sv_callers/second/NanoVar/nv_virtualenv/lib/python2.7/site-packages/matplotlib/path.py", line 21, in <module>
    from . import _path, rcParams
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /hpc/home/szw190/NANOPORE/sv_callers/second/NanoVar/lib/libstdc++.so.6)
/ri/shared/modules/bedtools/2.27.1/bin/bedtools: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /hpc/home/szw190/NANOPORE/sv_callers/second/NanoVar/lib/libstdc++.so.6)
/ri/shared/modules/bedtools/2.27.1/bin/bedtools: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /hpc/home/szw190/NANOPORE/sv_callers/second/NanoVar/lib/libstdc++.so.6)
/ri/shared/modules/bedtools/2.27.1/bin/bedtools: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by /hpc/home/szw190/NANOPORE/sv_callers/second/NanoVar/lib/libstdc++.so.6)
Traceback (most recent call last):
  File "/hpc/home/szw190/NANOPORE/sv_callers/second/NanoVar/scripts/nv_breakpoint_parser.py", line 197, in <module>
    print str(read_name) + '\t' + str(bp2-10) + '\t' + str(bp2) + '\t' + str(bp_name) + ' ' + str(nov_ins_size) + '\t' + str(chrom) + '\t' + str(coord2) + '\t' + str(uniqidx) + '\t' + str('Nov2') + '\t' + str(uniqname) + '\t' + str(signature)
IOError: [Errno 32] Broken pipe
***SV Parse file required***---- ]  (35%)
Error: Intermediate test files corrupted, try 'make distclean' and rebuild
make: *** [check] Error 1
```

Here are the new log files from the process: 
[23-Aug~10-45-38_NanoVar.command.log](https://github.com/benoukraflab/NanoVar/files/3535044/23-Aug.10-45-38_NanoVar.command.log)
[23-Aug~10-45-38_NanoVar.log](https://github.com/benoukraflab/NanoVar/files/3535045/23-Aug.10-45-38_NanoVar.log)

I'm going to try to install this on a different machine in the meantime to see if it's my linux setup that's causing the issues. I'll let you know how that goes.

**Comment by cytham** [comment]
You're welcome, its my pleasure.

Seems like it requires libc.so.6 too, I have added it, feel free to try again.

**Comment by sage-wright** [comment]
The error pops up a bit sooner this time-- complains about GLIBC_PRIVATE's lack of definition?

```
NanoVar initiated --- Fri Aug 23 11:41:19 EDT 2019
python: relocation error: /lib64/libpthread.so.0: symbol __vdso_clock_gettime, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
python: relocation error: /lib64/libpthread.so.0: symbol __vdso_clock_gettime, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
date: relocation error: /lib64/libpthread.so.0: symbol __vdso_clock_gettime, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
python: relocation error: /lib64/libpthread.so.0: symbol __vdso_clock_gettime, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
***SV detect file required!***
Error: Intermediate test files corrupted, try 'make distclean' and rebuild
make: *** [check] Error 1
```

[23-Aug~11-41-19_NanoVar.log](https://github.com/benoukraflab/NanoVar/files/3535225/23-Aug.11-41-19_NanoVar.log)
[23-Aug~11-41-19_NanoVar.command.log](https://github.com/benoukraflab/NanoVar/files/3535226/23-Aug.11-41-19_NanoVar.command.log)

**Comment by cytham** [comment]
Thanks for trying it out. I think the error arises from the different versions between the lib I provide and the one you have in your system. Hence, providing the lib is not a feasible method, I am quite naive to try it.

I guess you can either continue to try to work things out with installing GLIBC locally, or request your administrator to upgrade the global libraries. Really sorry that you are facing this problem.

**Comment by tjiangHIT** [comment]
Hi @cytham ,
I have the same problem. Before make check, everything looks OK. When make check, it shows something like below:

Making check in scripts
make[1]: Entering directory '/home/tjiang/Tools/NanoVar/scripts'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/home/tjiang/Tools/NanoVar/scripts'
make[1]: Entering directory '/home/tjiang/Tools/NanoVar'
make[1]: Nothing to be done for 'check-am'.
make[1]: Leaving directory '/home/tjiang/Tools/NanoVar'
Testing unit...
Pre-testing...
Testing TensorFlow...
/bin/bash: /home/tjiang/Tools/NanoVar/nv_virtualenv/bin/activate: No such file or directory
DeprecationWarning: 'source deactivate' is deprecated. Use 'conda deactivate'.
Pre-testing passed
Post-testing...
/home/tjiang/Tools/NanoVar/scripts/nanovar: line 85: /home/tjiang/Tools/NanoVar/nv_virtualenv/bin/activate: No such file or directory
DeprecationWarning: 'source deactivate' is deprecated. Use 'conda deactivate'.
NanoVar initiated --- Mon Nov  4 08:08:25 UTC 2019
/home/tjiang/Tools/NanoVar/scripts/nanovar: line 656: /home/tjiang/Tools/NanoVar/nv_virtualenv/bin/activate: No such file or directory
***Overlap ANN file required!*** ]  (40%)
DeprecationWarning: 'source deactivate' is deprecated. Use 'conda deactivate'.
Error: Intermediate test files corrupted, try 'make distclean' and rebuild
Makefile:801: recipe for target 'check' failed
make: *** [check] Error 1

How can I fix this error?
Thanks.

tjiang

**Comment by cytham** [comment]
Hi tjiang, 

It seems like there's a problem with activating your python virtual environment. Can you do ```make distclean``` and try again to configure and make and make check? 

You need to make sure that the directory /home/tjiang/Tools/NanoVar/nv_virtualenv/ exist after compiling. If it exists, then its bin should contain a file called 'activate'. 

Can you also tell me your default python version and linux distribution?

Thanks

Cheng Yong

**Comment by tjiangHIT** [comment]
Hi @cytham ,
Thanks for your prompt reply.
I have tried as your recommendation, however, it was still not work. And I am sure the corresponding directory exist after compiling. 
My OS is Ubuntu 16.04.
BTW, I did the following before compiling:
> conda create --name nanovar python=2.7
> conda activate nanovar
> conda install samtools bedtools tensorflow
> git clone https://github.com/benoukraflab/NanoVar.git
> cd NanoVar
> ./configure --disable-bowtie2
> make -j 8
> make check

Are these commands causing the error?

tjiang

**Comment by cytham** [comment]
Hi tjiang,

Thanks for trying it out.

I think there might be errors during the ```make```. Can you please do ```make distclean``` again and do ```./configure --disable-bowtie2``` and ```make``` (with no ```-j 8```) and send me the output you see on screen.

Thanks,

Cheng Yong

**Comment by tjiangHIT** [comment]
Hello @cytham ,
I run **make distclean && ./configure --disable-bowtie2 && make**, the output is as follows.
[make.log](https://github.com/benoukraflab/NanoVar/files/3806812/make.log)
I knew the error was cause by **pythonvirten**, Hope you give some suggestions.
Thanks,
tjiang

**Comment by cytham** [comment]
Thanks for the log. I will look into it.

Meanwhile, if possible, can you try to install NanoVar without a conda environment.

Thanks

Cheng Yong

**Comment by tjiangHIT** [comment]
Hi @cytham ,
I installed it without the ***conda env*** successfully.
Thanks for your continued help.
Cheers.
tjiang

**Comment by cytham** [comment]
Hi tjang,

Thanks for raising your issue and letting me know.
I will work on the conda env problem and maybe make NanoVar available on bioconda for easier installation in the future.

Thanks,
Cheng Yong
