### ISSUE TITLE
 HS-BLAST output required!

### ISSUE THREAD

**Issue by jagos01** [benoukraflab/NanoVar---archived#5]
When running NanoVar I get the following error:
***HS-BLAST output required!***

I installed with ./configure --disable-bowtie2 because I do not need short reads.  Everything passed when make && make check was ran.  I have attached NanoVar.log.  Any ideas on how to resolve this issue would be appreciated?
Thanks,
Scott

[24-Oct~22-02-49_NanoVar.log](https://github.com/benoukraflab/NanoVar/files/3770319/24-Oct.22-02-49_NanoVar.log)

**Comment by cytham** [comment]
Hi Scott,

Thanks for using NanoVar and raising the issue.

I would advise doing a complete re-run of NanoVar: Delete any index files of your reference file (e.g. ref.fa.sequence, etc) and output the run to an empty output folder. An error might have occurred in your blast index files during previous runs and were skipped in your recent run of the log. A complete re-run should re-generate those files again and thus carry out the blast alignment successfully.

Can you also attach the "tmp' file found in output_dir/nanovar_run/hsblast_longreads. Thanks

Best,
Cheng Yong

**Comment by jagos01** [comment]
Thanks for you help.  I deleted my index files and re-ran NanoVar as suggested and everything worked.  Attached is the tmp file requested from the failed run.

[tmp.txt](https://github.com/benoukraflab/NanoVar/files/3799915/tmp.txt)

**Comment by cytham** [comment]
Great!
