### ISSUE TITLE
Error - SV Parse file required

### ISSUE THREAD

**Issue by jagos01** [benoukraflab/NanoVar---archived#6]
When running NanoVar I get the following error:
 
Traceback (most recent call last):  (32%)
  File "/home/dnd/NanoVar/scripts/nv_breakpoint_parser.py", line 177, in <module>
    coord1 = int(breakpointfile[i].split('\t')[6].split(' ')[1].split(',')[int(del_count - del_counter)].split(':')[1].split('-')[0])
IndexError: list index out of range
***SV Parse file required***---- ]  (35%)

NanoVar was installed with ./configure --disable-bowtie2 and everything passed when make && make check was ran. NanoVar finished without error on 3 other data sets.  I have attached NanoVar.log and NanoVar.commandlog. Any ideas on how to resolve this issue would be appreciated?

Thanks,
Scott

**Comment by cytham** [comment]
Hi Scott,

I think that might be a bug.

Can you please attach the logs and also attach a file that ends with *.SV0.95.tsv which can be found in ./nanovar_run/hsblast_longreads/.

Thanks
Cheng Yong

**Comment by jagos01** [comment]
Hello, 
Thank you for your reply.  I have attached the requested files.  There is also file that ends with *.SV0.95.parse50.tsv but it is empty.
[05-Nov~06-16-24_NanoVar.log](https://github.com/benoukraflab/NanoVar/files/3836314/05-Nov.06-16-24_NanoVar.log)
[05-Nov~06-16-24_NanoVar.commandlog.txt](https://github.com/benoukraflab/NanoVar/files/3836318/05-Nov.06-16-24_NanoVar.commandlog.txt)

[K96243_H2_BC06.hsblast-Flye_Defalut_K96243_Archive_BC01_Raconx1_Medaka_Consensus.SV0.95.tsv.txt](https://github.com/benoukraflab/NanoVar/files/3836323/K96243_H2_BC06.hsblast-Flye_Defalut_K96243_Archive_BC01_Raconx1_Medaka_Consensus.SV0.95.tsv.txt)

**Comment by cytham** [comment]
Hi Scott

Thanks for the reply.

I think the cause of the error is the comma "," in your contig name " contig2,". Removing the comma "," (i.e. "contig2" ) should resolve the problem. 

Thanks,
Cheng Yong

**Comment by jagos01** [comment]
Yes the comma was the problem.  Thank you for your help again.
Scott
